name: multi_shift
description: A new project for marking attendance in multiple time in a shift
dependencies:
  flutter:
    sdk: flutter
  connectivity: ^0.4.2
  flutter_calendar: ^0.0.8
  validate: ^1.7.0
  intl: ^0.15.6
  flutter_html_view: "^0.3.1"
  cupertino_icons: ^0.1.0
  simple_permissions: ^0.1.6
  location: ^1.4.1
  geocoder: ^0.1.1
  dio: ^1.0.6
  json_annotation: ^0.2.3
  shared_preferences: ^0.4.2
  image_picker: ^0.4.10
  path_provider: 0.4.1
  image: ^2.0.4
  flutter_launcher_icons: "^0.6.1"
  datetime_picker_formfield: ^0.1.3
  barcode_scan: ^0.0.3
  url_launcher: ^4.0.1
  charts_flutter: ^0.4.0
  splashscreen: ^1.1.0
  share: ^0.5.3
  launch_review: ^1.0.1

dev_dependencies:
 # flutter_test:
  #  sdk: flutter
  build_runner: ^0.9.0
  json_serializable: ^0.5.4

flutter_icons:
  android: true
  image_path: "assets/launch_logo.png"
  image_path_android: "assets/launch_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/diamond.png
    - assets/logo.png
    - assets/spinner.gif
    - assets/splash.gif
    - assets/launch_logo.png
    - assets/landing.png
    - assets/qr.png
    - assets/avatar.png
    - assets/add_admin.png
    - assets/mark_attendance.png
    - assets/reqtimeoff.png
    - assets/att_log.png
    - assets/visitlog.png
    - assets/changepwd.png
    - assets/editprofile.png
    - assets/attreport.png
    - assets/config.png
    - assets/addemp.png
    - assets/timeofflog.png
    - assets/empvisit.png